### ISSUE TITLE
next-updater does not support the latest atmosphere

### ISSUE THREAD

**Issue by carcaschoi** [mistervampi/NeXT#12]

**Comment by mistervampi** [comment]
Actually, it does
![2021092522190900-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/43819059/134792213-0e10fb46-c4f9-4e82-b868-346c030b8f04.jpg)
.

**Comment by carcaschoi** [comment]
If the app doesn't get the next version, it crashes

**Comment by mistervampi** [comment]
But i don't see the issue at all. NeXT version must be present in every update.

**Comment by carcaschoi** [comment]
I use other aio package so next version is not presented.

**Comment by mistervampi** [comment]
NeXT updater is intended to be used only on NeXT. There's nosense using it with other AIO.
