### ISSUE TITLE
FTP - firmware 13.0.0

### ISSUE THREAD

**Issue by Borrajo** [mistervampi/NeXT#13]
Vampi, que tal? probaste el modulo FTP en firmware 13.0.0 con atmosphere 1.1.1 ? 
tiene un error que no permite el acceso a la raiz, da error 550. Con Next te funciona bien?

**Comment by mistervampi** [comment]
Saludos, de hecho si lo he testeado hoy mismo y funciona perfectamente.

**Comment by Borrajo** [comment]
Si, estuve investigando más y hay un error cuando se activa el bootprotect de hekate pero solo falla en el firmware 13.0.0, asumo entonces que en Next no está configurado eso. Si queres hacé la prueba y asi verificamos ese comportamiento

**Comment by skylex77** [comment]
Amigos saben si esta version funciona con el 13.1.0?
