### ISSUE TITLE
Cannot boot mariko

### ISSUE THREAD

**Issue by blackheartme** [mistervampi/NeXT#7]
Hello i tried to use next 2.0 with mariko unit, i replace the boot.dat with sxgear boot.dat as instructed in readme, but so far i cant boot, any complete tutorial for mariko?

**Comment by mistervampi** [comment]
Did you put the BOOT.INI file on the root of the SD?
![image](https://user-images.githubusercontent.com/43819059/109406281-c7663280-7945-11eb-84e6-6ae05e334bc0.png)

**Comment by Wuhey13** [comment]
Hi I'd like to try the new NeXT 2.04 on my Mariko FW 11.0.0 . could you please let me what shall i do with the SXgear file ? Thanks

**Comment by mistervampi** [comment]
> Hi I'd like to try the new NeXT 2.04 on my Mariko FW 11.0.0 . could you please let me what shall i do with the SXgear file ? Thanks

Sadly NeXT Bootmenu isn't supported by Mariko units because HWINIT in the code is kinda old and only supports Erista units.  I'm trying to update it but right now i don't have a Mariko Switch for testing, For now you have to boot with Hekate payload to make it work. 

Sorry about that.
