### ISSUE TITLE
Can not boot SXOS bottom?

### ISSUE THREAD

**Issue by Shan-Mk** [mistervampi/NeXT#8]
Hello i tried to use next 2.0 boot sxos but this sxos button not working !! pls fix it thx guys
can fix use sxos.bin to boot  sxos?
because mariko machine used sxgrear boot.dat next 2.0 not use  sxos 3.1 boot.dat

**Comment by fatiianywhere** [comment]
I have the same problem

**Comment by Shan-Mk** [comment]
Main menu SXOS button is freeze not working Next 2.01 is same   pls check fixed it !! thank you 
but hekate is working

**Comment by mistervampi** [comment]
Sorry for the late answer.

You are right. I found an issue with the boot procedure for SX OS on the bootmenu code.

I will launch a fix ASAP

**Comment by mistervampi** [comment]
NeXT 2.02 comes with a fix for SX OS.
